[package]
name = "footsies_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
godot = "0.2.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lib]
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.

[build]
rustflags = ["-C", "target-feature=+sse2"]
